export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";
export const ADD_ANSWER = "ADD_ANSWER";
export const UPDATE_LAST_ANSWERED_Q_INDEX = "UPDATE_LAST_ANSWERED_Q_INDEX";
export const FETCHING_USER_SUCCESS = "FETCHING_USER_SUCCESS";
export const FETCHING_USER = "FETCHING_USER";
export const FETCHING_USER_ERROR = "FETCHING_USER_ERROR";
